# Gradle Properties
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true
org.gradle.workers.max = 3

# Gradle Plugins
shadow_version = 9.3.0

# Project Properties
version = 0.1.0-SNAPSHOT
group = eu.ponei
archivesBaseName = converter

# Project Dependencies
mappingio_version = 0.8.0
junit_jupiter_version = 5.13.4
